options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'app', '--runtime', 'nodejs20', '--trigger-http', '--allow-unauthenticated', '--gen2', '--region', 'us-central1']
