steps:
- name: 'gcr.io/cloud-builders/npm'
args: ['install']
- name: 'gcr.io/cloud-builders/npm'
args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
args: ['functions', 'deploy', 'app', '--runtime', 'nodejs20', '--trigger-http',
'--allow-unauthenticated']
- name: 'gcr.io/cloud-builders/gcloud'
args: ['functions', 'deploy', 'app', '--runtime', 'nodejs20', '--trigger-http',
'--allow-unauthenticated']
- name: 'gcr.io/cloud-builders/gcloud'
args: ['functions', 'deploy', 'app', '--runtime', 'nodejs20', '--trigger-http',
'--allow-unauthenticated']
- name: 'gcr.io/cloud-builders/gcloud'
args: ['functions', 'deploy', 'app', '--runtime', 'nodejs20', '--trigger-http',
'--allow-unauthenticated']